using System.Collections.Generic;
using System.Linq;
using LoldoAllChamp.Models;

namespace LoldoAllChamp.Services
{
    public static class ChampionService
    {
        public static List<Champion> GetAllChampions()
        {
            var champions = new List<Champion>
            {
                new() { Id = "Aatrox", Name = "Aatrox" },
                new() { Id = "Ahri", Name = "Ahri" },
                new() { Id = "Akali", Name = "Akali" },
                new() { Id = "Akshan", Name = "Akshan" },
                new() { Id = "Alistar", Name = "Alistar" },
                new() { Id = "Ambessa", Name = "Ambessa" },
                new() { Id = "Amumu", Name = "Amumu" },
                new() { Id = "Anivia", Name = "Anivia" },
                new() { Id = "Annie", Name = "Annie" },
                new() { Id = "Aphelios", Name = "Aphelios" },
                new() { Id = "Ashe", Name = "Ashe" },
                new() { Id = "AurelionSol", Name = "Aurelion Sol" },
                new() { Id = "Aurora", Name = "Aurora" },
                new() { Id = "Azir", Name = "Azir" },
                new() { Id = "Bard", Name = "Bard" },
                new() { Id = "Belveth", Name = "Bel'Veth" },
                new() { Id = "Blitzcrank", Name = "Blitzcrank" },
                new() { Id = "Brand", Name = "Brand" },
                new() { Id = "Braum", Name = "Braum" },
                new() { Id = "Briar", Name = "Briar" },
                new() { Id = "Caitlyn", Name = "Caitlyn" },
                new() { Id = "Camille", Name = "Camille" },
                new() { Id = "Cassiopeia", Name = "Cassiopeia" },
                new() { Id = "Chogath", Name = "Cho'Gath" },
                new() { Id = "Corki", Name = "Corki" },
                new() { Id = "Darius", Name = "Darius" },
                new() { Id = "Diana", Name = "Diana" },
                new() { Id = "Draven", Name = "Draven" },
                new() { Id = "DrMundo", Name = "Dr. Mundo" },
                new() { Id = "Ekko", Name = "Ekko" },
                new() { Id = "Elise", Name = "Elise" },
                new() { Id = "Evelynn", Name = "Evelynn" },
                new() { Id = "Ezreal", Name = "Ezreal" },
                new() { Id = "Fiddlesticks", Name = "Fiddlesticks" },
                new() { Id = "Fiora", Name = "Fiora" },
                new() { Id = "Fizz", Name = "Fizz" },
                new() { Id = "Galio", Name = "Galio" },
                new() { Id = "Gangplank", Name = "Gangplank" },
                new() { Id = "Garen", Name = "Garen" },
                new() { Id = "Gnar", Name = "Gnar" },
                new() { Id = "Gragas", Name = "Gragas" },
                new() { Id = "Graves", Name = "Graves" },
                new() { Id = "Gwen", Name = "Gwen" },
                new() { Id = "Hecarim", Name = "Hecarim" },
                new() { Id = "Heimerdinger", Name = "Heimerdinger" },
                new() { Id = "Hwei", Name = "Hwei" },
                new() { Id = "Illaoi", Name = "Illaoi" },
                new() { Id = "Irelia", Name = "Irelia" },
                new() { Id = "Ivern", Name = "Ivern" },
                new() { Id = "Janna", Name = "Janna" },
                new() { Id = "JarvanIV", Name = "Jarvan IV" },
                new() { Id = "Jax", Name = "Jax" },
                new() { Id = "Jayce", Name = "Jayce" },
                new() { Id = "Jhin", Name = "Jhin" },
                new() { Id = "Jinx", Name = "Jinx" },
                new() { Id = "Kaisa", Name = "Kai'Sa" },
                new() { Id = "Kalista", Name = "Kalista" },
                new() { Id = "Karma", Name = "Karma" },
                new() { Id = "Karthus", Name = "Karthus" },
                new() { Id = "Kassadin", Name = "Kassadin" },
                new() { Id = "Katarina", Name = "Katarina" },
                new() { Id = "Kayle", Name = "Kayle" },
                new() { Id = "Kayn", Name = "Kayn" },
                new() { Id = "Kennen", Name = "Kennen" },
                new() { Id = "Khazix", Name = "Kha'Zix" },
                new() { Id = "Kindred", Name = "Kindred" },
                new() { Id = "Kled", Name = "Kled" },
                new() { Id = "KogMaw", Name = "Kog'Maw" },
                new() { Id = "KSante", Name = "K'Sante" },
                new() { Id = "Leblanc", Name = "LeBlanc" },
                new() { Id = "LeeSin", Name = "Lee Sin" },
                new() { Id = "Leona", Name = "Leona" },
                new() { Id = "Lillia", Name = "Lillia" },
                new() { Id = "Lissandra", Name = "Lissandra" },
                new() { Id = "Lucian", Name = "Lucian" },
                new() { Id = "Lulu", Name = "Lulu" },
                new() { Id = "Lux", Name = "Lux" },
                new() { Id = "Malphite", Name = "Malphite" },
                new() { Id = "Malzahar", Name = "Malzahar" },
                new() { Id = "Maokai", Name = "Maokai" },
                new() { Id = "MasterYi", Name = "Master Yi" },
                new() { Id = "Mel", Name = "Mel" },
                new() { Id = "Milio", Name = "Milio" },
                new() { Id = "MissFortune", Name = "Miss Fortune" },
                new() { Id = "Mordekaiser", Name = "Mordekaiser" },
                new() { Id = "Morgana", Name = "Morgana" },
                new() { Id = "Naafiri", Name = "Naafiri" },
                new() { Id = "Nami", Name = "Nami" },
                new() { Id = "Nasus", Name = "Nasus" },
                new() { Id = "Nautilus", Name = "Nautilus" },
                new() { Id = "Neeko", Name = "Neeko" },
                new() { Id = "Nidalee", Name = "Nidalee" },
                new() { Id = "Nilah", Name = "Nilah" },
                new() { Id = "Nocturne", Name = "Nocturne" },
                new() { Id = "Nunu", Name = "Nunu & Willump" },
                new() { Id = "Olaf", Name = "Olaf" },
                new() { Id = "Orianna", Name = "Orianna" },
                new() { Id = "Ornn", Name = "Ornn" },
                new() { Id = "Pantheon", Name = "Pantheon" },
                new() { Id = "Poppy", Name = "Poppy" },
                new() { Id = "Pyke", Name = "Pyke" },
                new() { Id = "Qiyana", Name = "Qiyana" },
                new() { Id = "Quinn", Name = "Quinn" },
                new() { Id = "Rakan", Name = "Rakan" },
                new() { Id = "Rammus", Name = "Rammus" },
                new() { Id = "RekSai", Name = "Rek'Sai" },
                new() { Id = "Rell", Name = "Rell" },
                new() { Id = "Renata", Name = "Renata Glasc" },
                new() { Id = "Renekton", Name = "Renekton" },
                new() { Id = "Rengar", Name = "Rengar" },
                new() { Id = "Riven", Name = "Riven" },
                new() { Id = "Rumble", Name = "Rumble" },
                new() { Id = "Ryze", Name = "Ryze" },
                new() { Id = "Samira", Name = "Samira" },
                new() { Id = "Sejuani", Name = "Sejuani" },
                new() { Id = "Senna", Name = "Senna" },
                new() { Id = "Seraphine", Name = "Seraphine" },
                new() { Id = "Sett", Name = "Sett" },
                new() { Id = "Shaco", Name = "Shaco" },
                new() { Id = "Shen", Name = "Shen" },
                new() { Id = "Shyvana", Name = "Shyvana" },
                new() { Id = "Singed", Name = "Singed" },
                new() { Id = "Sion", Name = "Sion" },
                new() { Id = "Sivir", Name = "Sivir" },
                new() { Id = "Skarner", Name = "Skarner" },
                new() { Id = "Smolder", Name = "Smolder" },
                new() { Id = "Sona", Name = "Sona" },
                new() { Id = "Soraka", Name = "Soraka" },
                new() { Id = "Swain", Name = "Swain" },
                new() { Id = "Sylas", Name = "Sylas" },
                new() { Id = "Syndra", Name = "Syndra" },
                new() { Id = "TahmKench", Name = "Tahm Kench" },
                new() { Id = "Taliyah", Name = "Taliyah" },
                new() { Id = "Talon", Name = "Talon" },
                new() { Id = "Taric", Name = "Taric" },
                new() { Id = "Teemo", Name = "Teemo" },
                new() { Id = "Thresh", Name = "Thresh" },
                new() { Id = "Tristana", Name = "Tristana" },
                new() { Id = "Trundle", Name = "Trundle" },
                new() { Id = "Tryndamere", Name = "Tryndamere" },
                new() { Id = "TwistedFate", Name = "Twisted Fate" },
                new() { Id = "Twitch", Name = "Twitch" },
                new() { Id = "Udyr", Name = "Udyr" },
                new() { Id = "Urgot", Name = "Urgot" },
                new() { Id = "Varus", Name = "Varus" },
                new() { Id = "Vayne", Name = "Vayne" },
                new() { Id = "Veigar", Name = "Veigar" },
                new() { Id = "Velkoz", Name = "Vel'Koz" },
                new() { Id = "Vex", Name = "Vex" },
                new() { Id = "Vi", Name = "Vi" },
                new() { Id = "Viego", Name = "Viego" },
                new() { Id = "Viktor", Name = "Viktor" },
                new() { Id = "Vladimir", Name = "Vladimir" },
                new() { Id = "Volibear", Name = "Volibear" },
                new() { Id = "Warwick", Name = "Warwick" },
                new() { Id = "Wukong", Name = "Wukong" },
                new() { Id = "Xayah", Name = "Xayah" },
                new() { Id = "Xerath", Name = "Xerath" },
                new() { Id = "XinZhao", Name = "Xin Zhao" },
                new() { Id = "Yasuo", Name = "Yasuo" },
                new() { Id = "Yone", Name = "Yone" },
                new() { Id = "Yorick", Name = "Yorick" },
                new() { Id = "Yuumi", Name = "Yuumi" },
                new() { Id = "Zac", Name = "Zac" },
                new() { Id = "Zed", Name = "Zed" },
                new() { Id = "Zeri", Name = "Zeri" },
                new() { Id = "Ziggs", Name = "Ziggs" },
                new() { Id = "Zilean", Name = "Zilean" },
                new() { Id = "Zoe", Name = "Zoe" },
                new() { Id = "Zyra", Name = "Zyra" },
            };

            return champions.OrderBy(c => c.Name).ToList();
        }
    }
}
